Web/Models/ClassificacaoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class ClassificacaoModel
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
    }
}

Web/Models/ContatoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Empresa { get; set; }
        public string Endereco { get; set; }
        public List<TelefoneModel> Telefones { get; set; }
        public List<EmailModel> Emails { get; set; }

        public TelefoneModel Telefone1 { get; set; }
        public TelefoneModel Telefone2 { get; set; }
        public TelefoneModel Telefone3 { get; set; }

        public EmailModel Email1 { get; set; }
        public EmailModel Email2 { get; set; }
        public EmailModel Email3 { get; set; }

        public bool IsValid()
        {
            if (Nome == "" || Nome == null)
            {
                return false;
            }
            return true;
        }
    }
}

Web/Models/EmailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class EmailModel
    {
        public int Id { get; set; }
        public string Endereco { get; set; }
        public int IdClassificacao { get; set; }
        public ClassificacaoModel Classificacao { get; set; }
    }
}

Web/Models/ListaContatoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class ListaContatoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

Web/Models/TelefoneModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class TelefoneModel
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public int IdClassificacao { get; set; }
        public ClassificacaoModel Classificacao { get; set; }
    }
}

Web/Controllers/ContatoController.cs
using Aplicacao;
using Aplicacao.Servicos;
using AutoMapper;
using Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ContatoController : Controller
    {
        private IServicoContato _servicoContato;

        public ContatoController(IServicoContato servicoContato)
        {
            _servicoContato = servicoContato;
        }

        public ActionResult Index()
        {
            var contatos = _servicoContato.ObterTodosContatos().OrderBy(c => c.Nome);
            return View(Mapper.Map<List<ListaContatoModel>>(contatos));
        }

        public ActionResult Incluir()
        {
            //Refatorar
            List<ClassificacaoModel> classificacoes = new List<ClassificacaoModel>();
            classificacoes.Add( new ClassificacaoModel { Id = 1,  Descricao = "Casa" });
            classificacoes.Add(new ClassificacaoModel { Id = 2, Descricao = "Trabalho" });
            classificacoes.Add(new ClassificacaoModel { Id = 3, Descricao = "Outro" });
            ViewBag.Classificacoes = classificacoes;
            return View();
        }

        [HttpPost]
        public ActionResult Gravar(ContatoModel contato)
        {
            if (contato.IsValid())
            {
                //temporário Apenas para converter no obj os n telefones e emails de forma mais fácil
                //refatorar 
                List<TelefoneModel> telefones = new List<TelefoneModel>();
                if (contato.Telefone1.Numero != null)
                    telefones.Add(contato.Telefone1);
                if (contato.Telefone2.Numero != null)
                    telefones.Add(contato.Telefone2);
                if (contato.Telefone3.Numero != null)
                    telefones.Add(contato.Telefone3);
                contato.Telefones = telefones;
                //refatorar 
                List<EmailModel> emails = new List<EmailModel>();
                if (contato.Email1.Endereco != null)
                    emails.Add(contato.Email1);
                if (contato.Email2.Endereco != null)
                    emails.Add(contato.Email2);
                if (contato.Email3.Endereco != null)
                    emails.Add(contato.Email3);
                contato.Emails = emails;

                _servicoContato.SalvarContato(Mapper.Map<Contato>(contato));
                return RedirectToAction("Index");
            }
            else
            {
                return View(contato);
            }
        }

        public ActionResult Editar(int id)
        {
            var contato = _servicoContato.SelecionarContato(id);
            return View(Mapper.Map<ContatoModel>(contato));
        }

        public ActionResult Visualizar(int id)
        {
            var contato = _servicoContato.SelecionarContato(id);
            return View(Mapper.Map<ContatoModel>(contato));
        }

        [HttpPost]
        public ActionResult Deletar(int id)
        {
            _servicoContato.DeletarContato(id);

            var contatos = _servicoContato.ObterTodosContatos().OrderBy(c => c.Nome);
 
            return Json(Mapper.Map<List<ListaContatoModel>>(contatos));
        }
        
    }
}

Web/Views/Contato/Editar.cshtml
@model  Web.Models.ContatoModel
@{
    ViewBag.Title = "Editar";
}

<h2>Editar Contato</h2>

@using (Html.BeginForm("Gravar", "Contato", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>
<script src="~/Scripts/jquery.validate.min.js" />
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" />

Web/Views/Contato/Incluir.cshtml
@model  Web.Models.ContatoModel
@{
    ViewBag.Title = "Incluir";
}

<h2>Incluir Contato</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">

                <h3>Telefones</h3>
                <table>
                    <thead>
                        <tr>
                            <th>
                                Número
                            </th>
                            <th>
                                Tipo
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.EditorFor(model => model.Telefone1.Numero, new { htmlAttributes = new { @class = "form-control" } })</td>
                            <td>
                                @Html.DropDownListFor(model => model.Telefone1.IdClassificacao, new SelectList(ViewBag.Classificacoes, "Id", "Descricao"), new { @class = "form-control" })
                            </td>
                        </tr>
                        <tr>
                            <td>@Html.EditorFor(model => model.Telefone2.Numero, new { htmlAttributes = new { @class = "form-control" } })</td>
                            <td>
                                @Html.DropDownListFor(model => model.Telefone2.IdClassificacao, new SelectList(ViewBag.Classificacoes, "Id", "Descricao"), new { @class = "form-control" })
                            </td>
                        </tr>
                        <tr>
                            <td>@Html.EditorFor(model => model.Telefone3.Numero, new { htmlAttributes = new { @class = "form-control" } })</td>
                            <td>
                                @Html.DropDownListFor(model => model.Telefone3.IdClassificacao, new SelectList(ViewBag.Classificacoes, "Id", "Descricao"), new { @class = "form-control" })
                            </td>
                        </tr>

                    </tbody>
                </table>
                <h3>Emails</h3>
                <table>
                    <thead>
                        <tr>
                            <th>
                                E-mail
                            </th>
                            <th>
                                Tipo
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.EditorFor(model => model.Email1.Endereco, new { htmlAttributes = new { @class = "form-control" } })</td>
                            <td>
                                @Html.DropDownListFor(model => model.Email1.IdClassificacao, new SelectList(ViewBag.Classificacoes, "Id", "Descricao"), new { @class = "form-control" })
                            </td>
                        </tr>
                        <tr>
                            <td>@Html.EditorFor(model => model.Email2.Endereco, new { htmlAttributes = new { @class = "form-control" } })</td>
                            <td>
                                @Html.DropDownListFor(model => model.Email2.IdClassificacao, new SelectList(ViewBag.Classificacoes, "Id", "Descricao"), new { @class = "form-control" })
                            </td>
                        </tr>
                        <tr>
                            <td>@Html.EditorFor(model => model.Email3.Endereco, new { htmlAttributes = new { @class = "form-control" } })</td>
                            <td>
                                @Html.DropDownListFor(model => model.Email3.IdClassificacao, new SelectList(ViewBag.Classificacoes, "Id", "Descricao"), new { @class = "form-control" })
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" formaction="Gravar" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>
<script src="~/Scripts/jquery.validate.min.js" />
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" />

Web/Views/Contato/Index.cshtml
@model List<Web.Models.ListaContatoModel>
@{
    ViewBag.Title = "Index";
}


<h2>Contatos</h2>
<input type="text" id="txtPesquisar" onkeyup="pesquisar()" placeholder="Pesquisar" class="form-control">
<table class="table" id="tblContatos">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var contato in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(contato.Nome, "Visualizar", new { id = contato.Id })
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = contato.Id }, new { @class = "btn btn-success btn-sm" })
                    <button type="button" class="btn-link btn btn-secondary btn-sm" data-item="@contato.Id">Excluir</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    @Html.ActionLink("Adicionar Contato", "Incluir")
</p>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".btn-link").click(function () {
                var id = $(this).attr('data-item');
                if (confirm("Deseja Remover este contato?")) {
                    $.ajax({
                        method: "POST",
                        url: "/Contato/Deletar/" + id,
                        success: function (data) {
                            $("#tblContatos tbody > tr").remove();
                            $.each(data, function (i, contato) {
                                $("#tblContatos tbody").append(
                                    "<tr>" +
                                    "   <td><a href='/Contato/Visualizar/'" + contato.Id + " >" + contato.Nome + "</a></td>" +
                                    "   <td>" +
                                    "       <a href='/Contato/Editar/" + contato.Id + "' class='btn btn-success btn-sm'>Editar</a>" +
                                    "       <button type=\"button\" class=\"btn-link btn btn-secondary btn-sm\" data-item=\"" + contato.Id + "\">Excluir</button>" +
                                    "   </td>" +
                                    "</tr>"
                                );
                            });
                        },
                        error: function (data) {
                            alert("Houve um erro na pesquisa.");
                        }
                    });
                }
            });
        });


        function pesquisar() {
            // Declare variables 
            var input, filter, table, tr, td, i;
            input = document.getElementById("txtPesquisar");
            filter = input.value.toUpperCase();
            table = document.getElementById("tblContatos");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
}

Web/Views/Contato/Visualizar.cshtml
@model  Web.Models.ContatoModel
@{
    ViewBag.Title = "Visualizar";
}

<h2>@Model.Nome</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

    </div>
    <div class="container">
        <h3>Contatos</h3>
        <ul class="list-group">
            @foreach (var telefone in Model.Telefones)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    @telefone.Numero
                    <span class="badge badge-pill badge-primary">@telefone.Classificacao.Descricao</span>
                </li>
            }
        </ul>

        <ul class="list-group">
            @foreach (var email in Model.Emails)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    @email.Endereco
                    <span class="badge badge-pill badge-primary">@email.Classificacao.Descricao</span>
                </li>
            }
        </ul>
    </div>


}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>
<script src="~/Scripts/jquery.validate.min.js" />
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" />

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contatos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>